apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  releaseName: podinfo
  targetNamespace: podinfo
  install:
    createNamespace: true # Ensures the namespace is created if it doesn’t exist
    remediation:
      retries: 3
  interval: 10m
  chart:
    spec:
      chart: podinfo
      version: "6.8.0"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  test:
    enable: false
  values:
    ingress:
      enabled: true
    replicaCount: 1
    service:
      type: ClusterIP # Default service type for internal load balancing
      port: 9898
      targetPort: 9898
      sessionAffinity: None
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 20m
        memory: 32Mi
    hpa:
      enabled: true
      maxReplicas: 30
      # average total CPU usage per pod (1-100)
      cpu: 70